---
abstract: unknown
author:
  - 'Shmuel Fomberg (semuelf@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Recorder
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 0
  HTML::Parser: 0
  HTML::TokeParser: 0
  HTTP::Proxy: 0
  HTTP::Request::Params: 0
  LWP::UserAgent: 0
  Pod::Usage: 0
  URI::Escape: 0
  URI::QueryParam: 0
resources:
  repository: https://github.com/semuel/perl-cpan-http-recorder.git
version: 0.07
